apiVersion: apps/v1
kind: Deployment
metadata:
  name: bradko-msa-member-depl
  namespace: bradko
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bradko-msa-member
  template:
    metadata:
      labels:
        app: bradko-msa-member
    spec:
      containers:
      - name: bradko-msa-member
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/bradkim-msa-member:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: ko-app-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: ko-app-secrets
              key: DB_PW
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: ko-app-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: ko-app-secrets
              key: AWS_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: bradko-msa-member-service
  namespace: bradko
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bradko-msa-member