apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  namespace: bradko-ns
  # labes는 service의 라우팅 대상이 되는 이름
  # service의 selector.app을 통해 매핑
  labels:
    app: my-nginx
spec:
  containers:
  - name: my-nginx
    image: nginx
    ports:
    - containerPort: 80